### ISSUE TITLE
Add App ID 

### ISSUE THREAD

**Issue by adam-lynch** [j201/windows-shortcuts#4]
Is there any chance that this module could support that? See http://electron.atom.io/docs/v0.36.5/tutorial/desktop-environment-integration/#windows;

> On Windows 8.1 and Windows 8, a shortcut to your app, with a [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459%28v=vs.85%29.aspx), must be installed to the Start screen. Note, however, that it does not need to be pinned to the Start screen.

And why it's such a pain without it: https://github.com/atom/electron/issues/4414.

Please :smile:

**Comment by j201** [comment]
Is this a feature that requires native code to support? If so, I'm reluctant, since this module is just a "dumb" interface to [shortcut.exe](http://www.optimumx.com/downloads.html), and doesn't have its own native code. If there was a way to add this feature incrementally (e.g., include a native executable that can modify existing shortcuts to have this feature), that might work.

**Comment by adam-lynch** [comment]
@j201 it does yeah. I ended up using a fork of a similar project to achieve this; see this method: https://github.com/kochiyaocean/windows-shortcuts#wsaddappidpath-appid-callback. You could use that. I don't mind since my problem is gone. Close if you like.
